name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy to server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Decrypt config file
        run: ./.github/scripts/decrypt-secret.sh
        env:
          SECRET_PASSPHRASE: ${{ secrets.CONFIG_ENCRYPTION_KEY }}
          SECRET_NAME: 'config.yml'
      - name: Add ansible PPA
        run: sudo apt-add-repository ppa:ansible/ansible
      - name: Upgrade ansible
        run: sudo apt-get install ansible -y
      - name: Install ansible docker collection
        run: ansible-galaxy collection install community.docker
      - name: Run ansible
        uses: dawidd6/action-ansible-playbook@v2.2.0
        with:
          playbook: 'playbook.yml'
          directory: ./
          key: ${{ secrets.SSH_KEY_SERVER_IUMS }}
          inventory: |
            [broker]
            ${{ secrets.IUMS_SERVER_IP }} ansible_user=${{ secrets.IUMS_USER }} ansible_python_interpreter=python3

            [process_repository]
            ${{ secrets.IUMS_SERVER_IP }} ansible_user=${{ secrets.IUMS_USER }} ansible_python_interpreter=python3

            [selfhealing]
            ${{ secrets.IUMS_SERVER_IP }} ansible_user=${{ secrets.IUMS_USER }} ansible_python_interpreter=python3
